All working bin/start

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-# TODO:
-#   - Expand all short form options like -p and -s
-
 user_input_jira_id="$1"
 
 confirm() {
@@ -11,6 +8,13 @@ confirm() {
   echo
   [[ "${input}" =~ ^[Yy]$ ]] && return 0 || return 1
 }
+
+
+# Fail without user input.
+if [ -z "$user_input_jira_id" ]; then
+  echo -e "\nJira ID required.\n"
+  exit 1
+fi
 
 
 # Fetch the Jira issue.
@@ -33,10 +37,10 @@ confirm "$issue_id: $issue_title?" || exit
 
 # Create the branch.
 
-# issue_type=$(echo "$response" | jq -r '.fields.issuetype.name')
-# branch="$issue_id-$issue_type"
-# echo "Creating $branch branch off of main..."
-# git checkout main && git pull && git checkout -b $branch
+issue_type=$(echo "$response" | jq -r '.fields.issuetype.name')
+branch=$(echo "$issue_id-$issue_type" | sed 's/ /-/g')
+echo "Creating '$branch' branch off of main..."
+git checkout main && git pull && git checkout -b "$branch"
 
 
 # Set Jira ticket "In Progress".
@@ -45,14 +49,19 @@ transition_url="$JIRA_BASE_URL/rest/api/latest/issue/$issue_id/transitions"
 response=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" "Content-Type: application/json" "$transition_url")
 in_progress_transition_id=$(echo "$response" | jq -r '.transitions[] | select(.name == "In Progress") | .id')
 transition_data='{"transition": {"id": "'"$in_progress_transition_id"'"}}'
-echo $transition_data
 response=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" -X POST -H "Content-Type: application/json" --data "$transition_data" "$transition_url")
 echo -e "\n$response\n"
 
 
 # Assign me to the ticket.
 
-# assignment_url="$JIRA_BASE_URL/rest/api/latest/issue/$issue_id"
-# assignment_data=='{ "fields": { "assignee": { "name": "'"$USERNAME"'" } } }' # TODO: Get user name
-# response=$(curl -u "$JIRA_EMAIL:$JIRA_TOKEN" -X PUT -H "Content-Type: application/json" --data "$assignement_data" "$assignment_url")
-# echo -e "\n$response\n"
+response=$(curl \
+  --silent \
+  --user "$JIRA_EMAIL:$JIRA_TOKEN" \
+  --header 'Accept: application/json' \
+  --header 'Content-Type: application/json' \
+  --request PUT \
+  --url "$JIRA_BASE_URL/rest/api/latest/issue/$issue_id/assignee" \
+  --data '{ "accountId": "'"$JIRA_ACCOUNT_ID"'" }'
+)
+echo -e "\n$response\n"
